[[constraint]]
  branch = "master"
  name = "github.com/johanbrandhorst/fetch"

[[constraint]]
  version = "1.1.0"
  name = "github.com/golang/protobuf"

[[constraint]]
  version = "1.12.0"
  name = "google.golang.org/grpc"

[prune]
  go-tests = true
  unused-packages = true
